# Generated by Django 4.1.7 on 2023-02-28 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_band_of_driver',
            field=models.CharField(choices=[('', 'Choose..'), ('1', '16 - 20'), ('2', '21 - 25'), ('3', '26 - 35'), ('4', '36 - 45'), ('5', '46 - 55'), ('6', '56 - 65'), ('7', '66 - 75'), ('8', 'Over 75')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_home_area_type',
            field=models.CharField(choices=[('', 'Choose..'), ('1', 'Urban area'), ('2', 'Small town'), ('3', 'Rural')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='engine_capacity_cc',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex_of_driver',
            field=models.CharField(choices=[('', 'Choose..'), ('1', 'Female'), ('2', 'Male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(choices=[('', 'Choose..'), ('1', 'Pedal cycle'), ('2', 'Motorcycle 50cc and under'), ('3', 'Motorcycle 125cc and under'), ('4', 'Motorcycle over 125cc and up to 500cc'), ('5', 'Motorcycle over 500cc'), ('6', 'Taxi/Private hire car'), ('7', 'Car'), ('8', 'Minibus (8 - 16 passenger seats)'), ('9', 'Bus or coach (17 or more pass seats)'), ('10', 'Agricultural vehicle'), ('11', 'Van / Goods 3.5 tonnes mgw or under'), ('12', 'Goods over 3.5t. and under 7.5t'), ('13', 'Goods 7.5 tonnes mgw and over'), ('14', 'Electric motorcycle'), ('15', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
