# Generated by Django 4.1.7 on 2023-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_profile_age_band_of_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20, null=True)),
                ('end', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(choices=[('', 'Choose..'), ('1', 'Motorcycle 50cc and under'), ('2', 'Motorcycle 125cc and under'), ('3', 'Motorcycle over 125cc and up to 500cc'), ('4', 'Motorcycle over 500cc'), ('5', 'Taxi/Private hire car'), ('6', 'Car'), ('7', 'Minibus (8 - 16 passenger seats)'), ('8', 'Bus or coach (17 or more pass seats)'), ('9', 'Agricultural vehicle'), ('10', 'Van / Goods 3.5 tonnes mgw or under'), ('11', 'Goods over 3.5t. and under 7.5t'), ('12', 'Goods 7.5 tonnes mgw and over'), ('13', 'Electric motorcycle'), ('14', 'Other')], max_length=10, null=True),
        ),
    ]
