# Generated by Django 4.1.7 on 2023-02-28 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_route_alter_profile_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('vehicle_type', models.CharField(choices=[('', 'Choose..'), ('1', 'Motorcycle 50cc and under'), ('2', 'Motorcycle 125cc and under'), ('3', 'Motorcycle over 125cc and up to 500cc'), ('4', 'Motorcycle over 500cc'), ('5', 'Taxi/Private hire car'), ('6', 'Car'), ('7', 'Minibus (8 - 16 passenger seats)'), ('8', 'Bus or coach (17 or more pass seats)'), ('9', 'Agricultural vehicle'), ('10', 'Van / Goods 3.5 tonnes mgw or under'), ('11', 'Goods over 3.5t. and under 7.5t'), ('12', 'Goods 7.5 tonnes mgw and over'), ('13', 'Electric motorcycle'), ('14', 'Other')], max_length=10, null=True)),
                ('sex_of_driver', models.CharField(choices=[('', 'Choose..'), ('1', 'Female'), ('2', 'Male')], max_length=10, null=True)),
                ('age_band_of_driver', models.CharField(choices=[('', 'Choose..'), ('1', '16 - 20'), ('2', '21 - 25'), ('3', '26 - 35'), ('4', '36 - 45'), ('5', '46 - 55'), ('6', '56 - 65'), ('7', '66 - 75'), ('8', 'Over 75')], max_length=10, null=True)),
                ('engine_capacity_cc', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
                ('driver_home_area_type', models.CharField(choices=[('', 'Choose..'), ('1', 'Urban area'), ('2', 'Small town'), ('3', 'Rural')], max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start', models.CharField(max_length=30, null=True)),
                ('end', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
