# Generated by Django 4.1.7 on 2023-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_user_input_delete_profile_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30, null=True)),
                ('destination', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='end',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='start',
        ),
        migrations.AlterField(
            model_name='user_input',
            name='age_band_of_driver',
            field=models.CharField(choices=[('', 'Choose..'), ('4', '16 - 20'), ('5', '21 - 25'), ('6', '26 - 35'), ('7', '36 - 45'), ('8', '46 - 55'), ('9', '56 - 65'), ('10', '66 - 75'), ('11', 'Over 75')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='sex_of_driver',
            field=models.CharField(choices=[('', 'Choose..'), ('1', 'Male'), ('2', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_input',
            name='vehicle_type',
            field=models.CharField(choices=[('', 'Choose..'), ('2', 'Motorcycle 50cc and under'), ('3', 'Motorcycle 125cc and under'), ('4', 'Motorcycle over 125cc and up to 500cc'), ('5', 'Motorcycle over 500cc'), ('8', 'Taxi/Private hire car'), ('9', 'Car'), ('10', 'Minibus (8 - 16 passenger seats)'), ('11', 'Bus or coach (17 or more pass seats)'), ('17', 'Agricultural vehicle'), ('19', 'Van / Goods 3.5 tonnes mgw or under'), ('20', 'Goods over 3.5t. and under 7.5t'), ('21', 'Goods 7.5 tonnes mgw and over'), ('23', 'Electric motorcycle'), ('90', 'Other')], max_length=10, null=True),
        ),
    ]
